using System;
using System.Collections.Generic;
using System.Text;
using System.Windows.Forms;
using DevExpress.XtraCharts;

namespace RegisterSummaryFunctionExample {
    public partial class Form1 : Form {
        const string summaryFunctionName = "PRODUCT";
        
        // Declare the Product summary function.
        private static SeriesPoint[] CalculateProductValue(
            Series series,
            object argument,
            string[] functionArguments,
            DataSourceValues[] values,
            object[] colors) {

            // Create an array of the resulting series points.
            List<SeriesPoint> points = new List<SeriesPoint>();
            // Calculate the resulting series points as Price * Count.
            for (int i = 0; i < values.Length; i++) {
                double value = Convert.ToDouble(values[i][functionArguments[0]]) *
                    Convert.ToDouble(values[i][functionArguments[1]]);
                if (value > 0)
                    points.Add(new SeriesPoint(argument, value));
            }
            // Return the result.
            return points.ToArray();
        }

        public Form1() {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            productsTableAdapter1.Fill(nwindDataSet1.Products);
        }

        String BuildSummaryFunction(String price, String count) {
            return
                new StringBuilder(summaryFunctionName)
                    .Append("([")
                    .Append(price)
                    .Append("],[")
                    .Append(count)
                    .Append("])")
                    .ToString();
        }

        private void Form1_Load(object sender, EventArgs e) {
            // Register the summary function in a chart.
            chartControl1.RegisterSummaryFunction("PRODUCT", "PRODUCT", 1,
                new SummaryFunctionArgumentDescription[] { 
                    new SummaryFunctionArgumentDescription("Price", ScaleType.Numerical), 
                    new SummaryFunctionArgumentDescription("Count", ScaleType.Numerical)},
                CalculateProductValue);

            Series series = chartControl1.Series["Product"];
            series.SummaryFunction = BuildSummaryFunction("UnitPrice", "UnitsOnOrder");
        }
    }
}
